# Generated by Django 3.0.5 on 2020-04-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('team1', models.CharField(max_length=50)),
                ('team2', models.CharField(max_length=50)),
                ('toss_winner', models.CharField(max_length=50)),
                ('toss_decision', models.CharField(max_length=20)),
                ('result', models.CharField(max_length=20)),
                ('dl_applied', models.IntegerField(max_length=2)),
                ('winner', models.CharField(max_length=50)),
                ('win_by_runs', models.IntegerField(max_length=5)),
                ('win_by_wickets', models.IntegerField(max_length=5)),
                ('player_of_match', models.CharField(max_length=30)),
                ('venue', models.CharField(max_length=50)),
                ('umpire1', models.CharField(blank=True, max_length=50, null=True)),
                ('umpire2', models.CharField(blank=True, max_length=50, null=True)),
                ('umpire3', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
