# Generated by Django 3.0.5 on 2020-04-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='dl_applied',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='matches',
            name='win_by_runs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='matches',
            name='win_by_wickets',
            field=models.IntegerField(),
        ),
    ]
