# Generated by Django 3.0.5 on 2020-04-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_auto_20200424_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='player_of_match',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='winner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
