# Generated by Django 3.0.5 on 2020-04-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_auto_20200424_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
