# Generated by Django 3.0.5 on 2020-04-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_deliveries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveries',
            name='total_runs',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
